### ISSUE TITLE
epoch and batchsize for miniImagenet and tieredImagenet

### ISSUE THREAD

**Issue by ghlili** [nupurkmr9/S2M2_fewshot#21]
Hello, sir , I want to know how many epochs and batchsize are used by miniImagenet and tieredImagenet in rotation and S2M2_R, respectively? thanks!!!!

**Comment by nupurkmr9** [comment]
Hi, for rotation supervision batch size is 64 otherwise 256. MiniImageNet is trained for 400 epochs and tieredImagNet is trained for 100 epochs with rotation self-supervision. Fine-tuning with manifold mixup is done for 100 and 50 more epochs respectively. Data augmentation is always used during backbone training.
